#!/bin/bash

set -e

export EMAIL=test@example.com

root=$(cd "$(dirname "$0")" && cd .. && pwd)
export PYTHONPATH="$root"

FURO2=${FURO2-"python3 -m furo2.furo2"}

main() {
    python3 --version
    git version
    $FURO2 version

    logsrepo=$(mktemp -d)
    logsdir=$(mktemp -d)
    logsdir2=$(mktemp -d)
    workdir=$(mktemp -d)

    git init --quiet --bare "$logsrepo"

    export FURO_LOGS_REPOSITORY="$logsrepo"
    export FURO_LOGS_DIR="$logsdir"

    cd "$workdir"
    git init --quiet
    git commit --quiet --allow-empty -m 'init'
    git config remote.origin.url https://git.example.com/u/repo

    $FURO2 exec echo 'Hello furoshiki!'
    $FURO2 history

    $FURO2 exec echo 'f  u'  'r  o'
    $FURO2 history
    $FURO2 history show HEAD | grep 'f  u r  o'
    test "$($FURO2 history -1 | wc -l)" -eq 1

    git config remote.origin.url ssh://git@git.example.com/u/repo
    test "$($FURO2 history -1 | wc -l)" -eq 1

    cat > "$workdir"/project.yml <<YAML
project: git.example.com/another/repo
YAML

    $FURO2 exec echo 'Hello another/repo!'
    $FURO2 history

    export FURO_LOGS_DIR="$logsdir2"
    $FURO2 history pull
    $FURO2 history

    if FURO_LOGS_REPOSITORY='' $FURO2 exec echo 'this must not be executed' 2> /dev/null | grep 'this must not be executed'; then
        die 'exec should not succeed when FURO_LOGS_REPOSITORY is empty'
    fi
}

die() {
    echo "$*" >&2
    exit 1
}

main
